// STUDENT LOGIN ACTIONS
export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_ERROR = 'STUDENT_LOGIN_ERROR'
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT'



// STUDENT REGISTER ACTIONS
export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST'
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS'
export const STUDENT_REGISTER_ERROR = 'STUDENT_REGISTER_ERROR'


// STUDENT PROFILE ACTIONS
export const STUDENT_CREATE_PROFILE_REQUEST = 'STUDENT_CREATE_PROFILE_REQUEST'
export const STUDENT_CREATE_PROFILE_SUCCESS = 'STUDENT_CREATE_PROFILE_SUCCESS'
export const STUDENT_CREATE_PROFILE_ERROR = 'STUDENT_CREATE_PROFILE_ERROR'